//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalCenter
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time
    {
        public int Id { get; set; }
        public System.TimeSpan Time1 { get; set; }
        public int DoctorId { get; set; }
        public int PatientId { get; set; }
        public int DateId { get; set; }
        public Nullable<int> VisitId { get; set; }
        public string Time_in_text { get; set; }
        public Nullable<int> Id_admin { get; set; }
        public Nullable<int> Id_service { get; set; }
    
        public virtual Admins Admins { get; set; }
        public virtual Date2 Date { get; set; }
        public virtual Doctors Doctors { get; set; }
        public virtual Patients Patients { get; set; }
        public virtual Services Services { get; set; }
        public virtual Visits Visits { get; set; }
    }
}
